import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Landpage.module.css";

import phoneHeader from "../assets/Landpage/png-phone.png";
import phone2 from "../assets/Landpage/png-phone2.png";
import phoneIcon from "../assets/Landpage/phone-icon.png";
import lockIcon from "../assets/Landpage/lock-icon.png";
import downloadIcon from "../assets/Landpage/download-icon.png";
import partners from "../assets/Landpage/partners.png";
import profile1 from "../assets/Landpage/profil-1.png";
import profile2 from "../assets/Landpage/profil-2.png";
import profile3 from "../assets/Landpage/profil-3.png";

import { useRouter } from "next/router";

export default function Home() {
   const router = useRouter();
   console.log(router.pathname);

   const handleClickLogin = () => {
      router.push("/login");
   };

   const handleClickRegister = () => {
      router.push("/register");
   };

   const handleClickTryIt = () => {
      router.push("/register");
   };

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <header className={`${styles["header-container"]}`}>
            <section className={`${styles["header"]}`}>
               <section className={`${styles["header-left"]}`}>
                  <div className={`${styles["tittle"]}`}>FazzPay</div>
                  <div className={`${styles["tittle-desc"]}`}>
                     <div className={`${styles["app-desc"]}`}>
                        Awesome App For Saving Time.
                     </div>
                     <div className={`${styles["mobile-desc"]}`}>
                        We bring you a mobile app for banking problems that
                        oftenly wasting much of your times.
                     </div>
                     <div
                        className={`${styles["try-btn"]}`}
                        onClick={handleClickTryIt}
                     >
                        Try It Free
                     </div>
                  </div>
               </section>
               <section className={`${styles["header-right"]}`}>
                  <div className={`${styles["auth-btn"]}`}>
                     <span
                        className={`${styles["login-btn"]}`}
                        onClick={handleClickLogin}
                     >
                        Login
                     </span>
                     <span
                        className={`${styles["register-btn"]}`}
                        onClick={handleClickRegister}
                     >
                        Sign Up
                     </span>
                  </div>
               </section>
            </section>
            <div className={`${styles["image"]}`}>
               <Image alt="Phone" src={phoneHeader} />
            </div>
         </header>

         <main className={`${styles["main"]}`}>
            <section className={`row ${styles["main-1"]} d-flex flex-column`}>
               <div
                  className={`d-flex justify-content-center text-center ${styles.about}`}
               >
                  About the Application.
               </div>
               <div
                  className={`d-flex justify-content-center text-center ${styles.weHave}`}
               >
                  We have some great features from the application and it`s
                  totally free to use by all users around the world.
               </div>
               <div className={`row justify-content-around ${styles.allBox}`}>
                  <span className={`col-3 ${styles.box}`}>
                     <div className={styles.icon}>
                        <div className={styles.aroundIcon}>
                           <Image
                              alt="phone"
                              src={phoneIcon}
                              width={20}
                              height={20}
                           />
                        </div>
                     </div>
                     <div className={`text-center ${styles.tittleBox}`}>
                        24/7 Support
                     </div>
                     <div className={`text-center ${styles.descBox}`}>
                        We have 24/7 contact support so you can contact us
                        whenever you want and we will respond it.
                     </div>
                  </span>
                  <span className={`col-3 ${styles.box}`}>
                     <div className={styles.icon}>
                        <div className={styles.aroundIcon}>
                           <Image
                              alt="phone"
                              src={lockIcon}
                              width={20}
                              height={20}
                           />
                        </div>
                     </div>
                     <div className={`text-center ${styles.tittleBox}`}>
                        Data Privacy
                     </div>
                     <div className={`text-center ${styles.descBox}`}>
                        We make sure your data is safe in our database and we
                        will encrypt any data you submitted to us.
                     </div>
                  </span>
                  <span className={`col-3 ${styles.box}`}>
                     <div className={styles.icon}>
                        <div className={styles.aroundIcon}>
                           <Image
                              alt="phone"
                              src={downloadIcon}
                              width={20}
                              height={20}
                           />
                        </div>
                     </div>
                     <div className={`text-center ${styles.tittleBox}`}>
                        Easy Download
                     </div>
                     <div className={`text-center ${styles.descBox}`}>
                        Zwallet is 100% totally free to use it`s now available
                        on Google Play Store and App Store.
                     </div>
                  </span>
               </div>
            </section>
            <section className={`row ${styles["main-2"]}`}>
               <span className={`col-6 ${styles["main-2-1"]}`}>
                  <div className={`${styles.tittleMain2}`}>
                     100+ Trusted Partners.
                  </div>
                  <div className={`${styles.descMain2}`}>
                     We have reached global level and have 100+ brand partners
                     around the globe.
                  </div>
               </span>
               <span className={`col-6 ${styles.partners}`}>
                  <Image
                     src={partners}
                     alt="partners-icon"
                     width={600}
                     height={350}
                  />
               </span>
            </section>
            <section className={`row ${styles["main-3"]}`}>
               <span className={`col-5 justify-content-end ${styles.phone2}`}>
                  <Image src={phone2} alt="phone 2" width={450} height={900} />
               </span>
               <span className={`col-7  ${styles.main3Text}`}>
                  <div className={`${styles.main3Tittle}`}>
                     All The Great FazzPay Features.
                  </div>
                  <div className={`${styles.containerBoxMain3}`}>
                     <div className={`${styles.boxMain3}`}>
                        <div>
                           <span className={`${styles.numberMain3}`}>1.</span>
                           <span className={`${styles.detailMain3}`}>
                              Small Fee
                           </span>
                        </div>
                        <div className={`${styles.detailDescMain3}`}>
                           We only charge 5% of every success transaction done
                           in FazzPay app.
                        </div>
                     </div>
                     <div className={`${styles.boxMain3}`}>
                        <div>
                           <span className={`${styles.numberMain3}`}>2.</span>
                           <span className={`${styles.detailMain3}`}>
                              Data Secured
                           </span>
                        </div>
                        <div className={`${styles.detailDescMain3}`}>
                           We only charge 5% of every success transaction done
                           in FazzPay app.
                        </div>
                     </div>
                     <div className={`${styles.boxMain3}`}>
                        <div>
                           <span className={`${styles.numberMain3}`}>3.</span>
                           <span className={`${styles.detailMain3}`}>
                              User Friendly
                           </span>
                        </div>
                        <div className={`${styles.detailDescMain3}`}>
                           We only charge 5% of every success transaction done
                           in FazzPay app.
                        </div>
                     </div>
                  </div>
               </span>
            </section>
            <section className={`row ${styles["main-4"]}`}>
               <div className={` ${styles.whatUsers}`}>
                  What Users are Saying.
               </div>
               <div className={`${styles.detailMain4}`}>
                  We have some great features from the application and it`s
                  totally free to use by all users around the world.
               </div>
               <div className={`row ${styles.containerComment}`}>
                  <span className={`col-3 ${styles.commentBox}`}>
                     <div className={`d-flex justify-content-center mt-5`}>
                        <Image
                           src={profile1}
                           alt="partners-icon"
                           width={50}
                           height={50}
                        />
                     </div>
                     <div
                        className={`d-flex justify-content-center ${styles.name}`}
                     >
                        Sherina Chaw
                     </div>
                     <div
                        className={`d-flex justify-content-center ${styles.comment}`}
                     >
                        “I use this app since 2 years ago and this is the best
                        app that I`ve ever use in my entire life”
                     </div>
                  </span>
                  <span className={`col-3 ${styles.commentBox}`}>
                     <div className={`d-flex justify-content-center mt-5`}>
                        <Image
                           src={profile2}
                           alt="partners-icon"
                           width={50}
                           height={50}
                        />
                     </div>
                     <div
                        className={`d-flex justify-content-center ${styles.name}`}
                     >
                        Jessica Mera
                     </div>
                     <div
                        className={`d-flex justify-content-center ${styles.comment}`}
                     >
                        “I use Zwallet to manage all financial needs. It`s super
                        easy to use and it`s 100% free app”
                     </div>
                  </span>
                  <span className={`col-3 ${styles.commentBox}`}>
                     <div className={`d-flex justify-content-center mt-5`}>
                        <Image
                           src={profile3}
                           alt="partners-icon"
                           width={50}
                           height={50}
                        />
                     </div>
                     <div
                        className={`d-flex justify-content-center ${styles.name}`}
                     >
                        Robert Chandler
                     </div>
                     <div
                        className={`d-flex justify-content-center ${styles.comment}`}
                     >
                        “Since I`m using this app, I`m not going to move to
                        another similar app. Thank you Zwallet!”
                     </div>
                  </span>
               </div>
            </section>
         </main>
         <footer className={`${styles.footer} w-100`}>
            <section className={`${styles.footerUp}`}>
               <div className={`${styles.fazzFoot}`}>FazzPay</div>
               <div className={`${styles.footDesc}`}>
                  Simplify financial needs and saving much time in banking needs
                  with one single app.
               </div>
            </section>
            <section
               className={`d-flex justify-content-between ${styles.footerDown}`}
            >
               <span className={`${styles.tradeMark}`}>
                  2020 FazzPay. All right reserved.
               </span>
               <span
                  className={`d-flex justify-content-between ${styles.rightFoot}`}
               >
                  <span className={`${styles.phone}`}>+62 5637 8882 9901</span>
                  <span className={`${styles.email}`}>contact@fazzpay.com</span>
               </span>
            </section>
         </footer>
      </>
   );
}
